# Generated by Django 3.0.2 on 2024-11-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.FloatField(default=0)),
                ('capacity', models.FloatField(default=0)),
                ('measure', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Station')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[('1', 'Aberta'), ('2', 'Confirmada'), ('0', 'Cancelada')], default='1')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Station')),
            ],
            options={
                'verbose_name': 'Pedido de Coleta',
                'verbose_name_plural': 'Pedidos de Coleta',
            },
        ),
    ]
