# Generated by Django 3.0.2 on 2024-11-23 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='measure',
        ),
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
